import time

print ("恭喜你找到了彩蛋，iodine为你献上一首《ECHO》（虽然不难找到但还是感谢你）")
print ("18.3s后开始播放")
time.sleep(18.3)
print("<console>:The clock stopped ticking forever ago")
time.sleep(3.3)
print("<console>:How long have I been up?")
time.sleep(2.0)
print("<console>:I don't know.")
time.sleep(1.0)
print("<console>:I can't get a grip,")
time.sleep(2.0)
print("<console>:But I can't let go")
time.sleep(2.0)
print("<console>:There wasn't anything")
time.sleep(1.0)
print("<console>:To hold onto though...")
time.sleep(2.0)
print("<console>:Why can't I see?")
time.sleep(2.0)
print("<console>:Why can't I see?")
time.sleep(2.0)
print("<console>:All the colors that you see?")
time.sleep(3.0)
print("<console>:Please, Can I be,")
time.sleep(2.0)
print("<console>:Please, Can I be")
time.sleep(2.0)
print("<console>:Colorful and free?")
time.sleep(3.0)
print("<console>:WHAT THE HELL'S GOING ON?!")
time.sleep(1.0)
print("<console>:CAN SOMEONE TELL ME PLEASE--")
time.sleep(2.0)
print("<console>:WHY, I'M SWITCHING FASTER THAN THE CHANNELS ON TV!!")
time.sleep(3.0)
print("<console>:I'M black, THEN I'M white!!")
time.sleep(1.5)
print("<console>:NO!!!")
time.sleep(0.3)
print("<console>:SOMETHING ISN'T RIGHT!!")
time.sleep(1.0)
print("<console>:MY ENEMY'S INVISIBLE, I DON'T KNOW HOW TO FIGHT!!")
time.sleep(3.0)
print("<console>:THE TREMBLING FEAR IS MORE THAN I CAN TAKE,")
time.sleep(2.0)
print("<console>:WHEN I'M UP AGAINST")
time.sleep(1.0)
print("<console>:THE ECHO IN THE MIRROR!!")
time.sleep(2.3)
print("<console>:ECHO!!")
time.sleep(6.3)
print("")
time.sleep(9.0)
print("<console>:I'm gonna burn my house down,")
time.sleep(4.0)
print("<console>:Into an ugly black.")
time.sleep(1.3)
print("<console>:I'm gonna run away, Now")
time.sleep(2.7)
print("<console>:And never look back.")
time.sleep(1.0)
print("<console>:I'm gonna burn my house down,")
time.sleep(2.0)
print("<console>:Into an ugly black.")
time.sleep(1.0)
print("<console>:I'm gonna run away, Now")
time.sleep(2.0)
print("<console>:And never look back.")
time.sleep(2.0)
print("<console>:I'm gonna run away down,")
time.sleep(1.2)
print("<console>:I'm gonna run away.")
time.sleep(1.2)
print("<console>:I'm gonna run away, Now")
time.sleep(1.5)
print("<console>:I'm gonna run away")
time.sleep(9.3)
print("<console>:I'm gonna burn my house down.")
time.sleep(1.3)
print("<console>:And never look back.")
time.sleep(1.3)
print("<console>:And never look back.")
time.sleep(1.5)
print("<console>:AND NEVER LOOK BACK!!")
time.sleep(1.2)
print("<console>:WHAT THE HELL'S GOING ON?!")
time.sleep(1.2)
print("<console>:CAN SOMEONE TELL ME PLEASE--")
time.sleep(2.0)
print("<console>:WHY, I'M SWITCHING FASTER THAN THE CHANNELS ON TV!!")
time.sleep(3.0)
print("<console>:I'M black, THEN I'M white!!")
time.sleep(1.5)
print("<console>:NO!!!")
time.sleep(0.3)
print("<console>:SOMETHING ISN'T RIGHT!!")
time.sleep(0.5)
print("<console>:MY ENEMY'S INVISIBLE, I DON'T KNOW HOW TO FIGHT!!")
time.sleep(3.0)
print("<console>:WHAT THE HELL'S GOING ON?!")
time.sleep(1.2)
print("<console>:CAN SOMEONE TELL ME PLEASE--")
time.sleep(2.0)
print("<console>:WHY, I'M SWITCHING FASTER THAN THE CHANNELS ON TV!!")
time.sleep(3.0)
print("<console>:I'M black, THEN I'M white!!")
time.sleep(1.5)
print("<console>:NO!!!")
time.sleep(0.3)
print("<console>:SOMETHING ISN'T RIGHT!!")
time.sleep(1.0)
print("<console>:MY ENEMY'S INVISIBLE, I DON'T KNOW HOW TO FIGHT!!")
time.sleep(4.0)
print("<console>:THE TREMBLING FEAR IS MORE THAN I CAN TAKE,")
time.sleep(2.0)
print("<console>:WHEN I'M UP AGAINST")
time.sleep(1.0)
print("<console>:THE ECHO IN THE MIRROR!!")
time.sleep(2.0)
print("<console>:THE TREMBLING FEAR IS MORE THAN I CAN TAKE,")
time.sleep(2.0)
print("<console>:WHEN I'M UP AGAINST")
time.sleep(1.0)
print("<console>:THE ECHO IN THE MIRROR!!")
